[package]
name = "luminos-config"
version = "0.1.0"
edition = "2024"
authors = ["joseph@raubstudios.com"]
description = "luminos config"
repository = "https://github.com/RaubJo/luminos-config"
license = "MIT"

[dependencies]
dotenv = "0.15"

[lints]
workspace = true
